const mainColors = {
  green1: '#0bcad4',
  green2: '#EDFCFD',
  green3: '#7DE1C9',
  dark1: '#112340',
  dark2: '#495A75',
  dark3: '#8092AF',
  gray1: '#7d8797',
  gray2: '#e9e9e9',
  gray3: '#EDEEF0',
  gray4: '#FBFBFB',
  gray5: 'rgba(255,255,255, 0.75)',
  gray6: '#DFDFDF',
  gray7: '#C4C4C4',
  blue1: '#0066CB',
  blue2: '#EDFCFD',
  black1: '#000000',
  black2: '#2B2B2B',
  black3: '#8A8A8A',
  red1: '#e06379',
};

export const colors = {
  container: mainColors.gray4,
  primary: mainColors.green3,
  secondary: mainColors.dark1,
  tertiary: mainColors.blue1,
  white: 'white',
  black: 'black',
  disable: mainColors.gray3,
  cardLight: mainColors.blue2,
  cardLight2: mainColors.green2,
  text: {
    primary: mainColors.black2,
    secondary: mainColors.green3,
    menuInActive: mainColors.dark2,
    menuActive: mainColors.green1,
    subTitle: mainColors.black3,
  },
  button: {
    primary: {
      background: mainColors.green3,
      text: 'white',
    },
    secondary: {
      background: mainColors.gray7,
      text: 'white',
    },
    bgBtnBack: mainColors.gray5,
  },
  border: mainColors.gray2,
  loadingBackground: mainColors.black2,
  textInputUnderline: mainColors.black2,
  totalBackground: mainColors.gray6,
  error: mainColors.red1,
};
