export const IS_LOADING = 'IS_LOADING';
export const DATA_USER = 'DATA_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const PANGINAPAN_START = 'PANGINAPAN_START';
export const PANGINAPAN_SUCCESS = 'PANGINAPAN_SUCCESS';
export const PANGINAPAN_FAIL = 'PANGINAPAN_FAIL';
export const PANGINAPAN_DETAIL_START = 'PANGINAPAN_DETAIL_START';
export const PANGINAPAN_DETAIL_SUCCESS = 'PANGINAPAN_DETAIL_SUCCESS';
export const PANGINAPAN_DETAIL_FAIL = 'PANGINAPAN_DETAIL_FAIL';

export const KAMAR_START = 'KAMAR_START';
export const KAMAR_SUCCESS = 'KAMAR_SUCCESS';
export const KAMAR_FAIL = 'KAMAR_FAIL';

export const PESANAN_USER_START = 'PESANAN_USER_START';
export const PESANAN_USER_SUCCESS = 'PESANAN_USER_SUCCESS';
export const DETAIL_PESANAN_USER_SUCCESS = 'DETAIL_PESANAN_USER_SUCCESS';
export const PESANAN_USER_FAIL = 'PESANAN_USER_FAIL';

export const BOOKING_START = 'BOOKING_START';
export const BOOKING_FINISH = 'BOOKING_FINISH';
