export const IS_LOADING = 'IS_LOADING';
export const DATA_USER = 'DATA_USER';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const PANGINAPAN_START = 'PANGINAPAN_START';
export const PANGINAPAN_SUCCESS = 'PANGINAPAN_SUCCESS';
export const PANGINAPAN_FAIL = 'PANGINAPAN_FAIL';
export const PANGINAPAN_DETAIL_START = 'PANGINAPAN_DETAIL_START';
export const PANGINAPAN_DETAIL_SUCCESS = 'PANGINAPAN_DETAIL_SUCCESS';
export const PANGINAPAN_DETAIL_FAIL = 'PANGINAPAN_DETAIL_FAIL';

export const KAMAR_START = 'KAMAR_START';
export const KAMAR_SUCCESS = 'KAMAR_SUCCESS';
export const KAMAR_FAIL = 'KAMAR_FAIL';
export const KAMAR_DELETE = 'KAMAR_DELETE';

export const PESANAN_USER_START = 'PESANAN_USER_START';
export const PESANAN_USER_SUCCESS = 'PESANAN_USER_SUCCESS';
export const DETAIL_PESANAN_USER_SUCCESS = 'DETAIL_PESANAN_USER_SUCCESS';
export const PESANAN_USER_FAIL = 'PESANAN_USER_FAIL';

export const BOOKING_START = 'BOOKING_START';
export const BOOKING_FINISH = 'BOOKING_FINISH';

export const WISATA_START = 'WISATA_START';
export const WISATA_SUCCESS = 'WISATA_SUCCESS';
export const WISATA_FAIL = 'WISATA_FAIL';
export const WISATA_DETAIL_START = 'WISATA_DETAIL_START';
export const WISATA_DETAIL_SUCCESS = 'WISATA_DETAIL_SUCCESS';
export const WISATA_DETAIL_FAIL = 'WISATA_DETAIL_FAIL';

export const KULINER_START = 'KULINER_START';
export const KULINER_SUCCESS = 'KULINER_SUCCESS';
export const KULINER_FAIL = 'KULINER_FAIL';
export const KULINER_DETAIL_START = 'KULINER_DETAIL_START';
export const KULINER_DETAIL_SUCCESS = 'KULINER_DETAIL_SUCCESS';
export const KULINER_DETAIL_FAIL = 'KULINER_DETAIL_FAIL';

export const OLEH_OLEH_START = 'OLEH_OLEH_START';
export const OLEH_OLEH_SUCCESS = 'OLEH_OLEH_SUCCESS';
export const OLEH_OLEH_FAIL = 'OLEH_OLEH_FAIL';
export const OLEH_OLEH_DETAIL_START = 'OLEH_OLEH_DETAIL_START';
export const OLEH_OLEH_DETAIL_SUCCESS = 'OLEH_OLEH_DETAIL_SUCCESS';
export const OLEH_OLEH_DETAIL_FAIL = 'OLEH_OLEH_DETAIL_FAIL';

export const DETAIL_START = 'DETAIL_START';
export const DETAIL_SUCCESS = 'DETAIL_SUCCESS';
export const DETAIL_FAIL = 'DETAIL_FAIL';

export const DESTINATION_START = 'DESTINATION_START';
export const DESTINATION_SUCCESS = 'DESTINATION_SUCCESS';
export const DESTINATION_FAIL = 'DESTINATION_FAIL';

export const AGENDA_START = 'AGENDA_START';
export const AGENDA_SUCCESS = 'AGENDA_SUCCESS';
export const AGENDA_FAIL = 'AGENDA_FAIL';
